const AGRI_DATA = {
  crops: [
    {
      id: "wheat",
      name: "Wheat",
      nameHi: "गेहूं",
      namePa: "ਕਣਕ",
      category: "cereals",
      image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🌾",
      grade: "FAQ Sharbati / HD-2967",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 2380,
      priceTrend: "+ ₹65 (2.8%)",
      trendDirection: "up",
      msp: 2275,
      season: "Rabi (रबी)",
      bestSowing: "Nov - Dec",
      harvestTime: "Mar - Apr",
      description: "High quality golden grain wheat with good protein and luster."
    },
    {
      id: "paddy",
      name: "Basmati Paddy",
      nameHi: "बासमती धान",
      namePa: "ਬਾਸਮਤੀ ਝੋਨਾ",
      category: "cereals",
      image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🌾",
      grade: "Pusa 1121 / 1509",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 3750,
      priceTrend: "+ ₹120 (3.3%)",
      trendDirection: "up",
      msp: 2203,
      season: "Kharif (खरीफ)",
      bestSowing: "Jun - Jul",
      harvestTime: "Oct - Nov",
      description: "Aromatic long grain premium basmati paddy."
    },
    {
      id: "mustard",
      name: "Mustard",
      nameHi: "सरसों",
      namePa: "ਸਰ੍ਹੋਂ",
      category: "oilseeds",
      image: "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🌼",
      grade: "42% Oil Content Black",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 5420,
      priceTrend: "+ ₹90 (1.7%)",
      trendDirection: "up",
      msp: 5650,
      season: "Rabi (रबी)",
      bestSowing: "Sep - Oct",
      harvestTime: "Feb - Mar",
      description: "High oil content bold black mustard seeds."
    },
    {
      id: "potato",
      name: "Potato",
      nameHi: "आलू",
      namePa: "ਆਲੂ",
      category: "vegetables",
      image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🥔",
      grade: "Kufri Jyoti / Pukhraj",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 1450,
      priceTrend: "- ₹30 (-2.0%)",
      trendDirection: "down",
      msp: 0,
      season: "Rabi / Winter",
      bestSowing: "Oct - Nov",
      harvestTime: "Jan - Mar",
      description: "Fresh table potato, smooth skin, medium to large size."
    },
    {
      id: "onion",
      name: "Red Onion",
      nameHi: "लाल प्याज",
      namePa: "ਲਾਲ ਪਿਆਜ਼",
      category: "vegetables",
      image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🧅",
      grade: "Nasik / Garhwa Red",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 2650,
      priceTrend: "+ ₹180 (7.3%)",
      trendDirection: "up",
      msp: 0,
      season: "Kharif / Late Rabi",
      bestSowing: "May - Jun & Oct - Nov",
      harvestTime: "Dec - Jan & Apr - May",
      description: "Dry firm red onions, high shelf life."
    },
    {
      id: "tomato",
      name: "Tomato",
      nameHi: "टमाटर",
      namePa: "ਟਮਾਟਰ",
      category: "vegetables",
      image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🍅",
      grade: "Hybrid Desi / Himsona",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 1850,
      priceTrend: "+ ₹110 (6.3%)",
      trendDirection: "up",
      msp: 0,
      season: "All seasons",
      bestSowing: "Jul - Aug & Nov - Dec",
      harvestTime: "90 days after sowing",
      description: "Glossy red firm round tomatoes."
    },
    {
      id: "cotton",
      name: "Cotton",
      nameHi: "कपास / नरमा",
      namePa: "ਕਪਾਹ / ਨਰਮਾ",
      category: "cash_crops",
      image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "☁️",
      grade: "Medium / Long Staple BT",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 7150,
      priceTrend: "- ₹40 (-0.6%)",
      trendDirection: "down",
      msp: 6620,
      season: "Kharif (खरीफ)",
      bestSowing: "Apr - May",
      harvestTime: "Oct - Dec",
      description: "Clean white long staple cotton free from trash."
    },
    {
      id: "maize",
      name: "Maize / Corn",
      nameHi: "मक्का",
      namePa: "ਮੱਕੀ",
      category: "cereals",
      image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🌽",
      grade: "Yellow Hybrid Feed Grade",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 2150,
      priceTrend: "+ ₹40 (1.9%)",
      trendDirection: "up",
      msp: 2090,
      season: "Kharif & Rabi",
      bestSowing: "Jun - Jul & Oct - Nov",
      harvestTime: "Sep - Oct & Feb - Mar",
      description: "Bright yellow dried corn kernels with low moisture."
    },
    {
      id: "soybean",
      name: "Soybean",
      nameHi: "सोयाबीन",
      namePa: "ਸੋਇਆਬੀਨ",
      category: "oilseeds",
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🌱",
      grade: "Yellow Bold JS-9560",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 4680,
      priceTrend: "+ ₹75 (1.6%)",
      trendDirection: "up",
      msp: 4600,
      season: "Kharif (खरीफ)",
      bestSowing: "Jun - Jul",
      harvestTime: "Oct - Nov",
      description: "Clean yellow bold soybean seed, moisture < 10%."
    },
    {
      id: "chana",
      name: "Gram / Chana",
      nameHi: "चना",
      namePa: "ਛੋਲੇ",
      category: "pulses",
      image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🧆",
      grade: "Desi Chana Bold",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 6100,
      priceTrend: "+ ₹150 (2.5%)",
      trendDirection: "up",
      msp: 5440,
      season: "Rabi (रबी)",
      bestSowing: "Oct - Nov",
      harvestTime: "Mar - Apr",
      description: "High grade brown desi chana."
    },
    {
      id: "sugarcane",
      name: "Sugarcane",
      nameHi: "गन्ना",
      namePa: "ਗੰਨਾ",
      category: "cash_crops",
      image: "https://images.unsplash.com/photo-1589135233689-d41a766c1eb9?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🎋",
      grade: "Early Maturing CO-0238",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 380,
      priceTrend: "0 (0%)",
      trendDirection: "flat",
      msp: 315,
      season: "Annual",
      bestSowing: "Feb - Mar & Oct",
      harvestTime: "Nov - Apr",
      description: "High recovery sweet thick sugarcane."
    },
    {
      id: "garlic",
      name: "Garlic",
      nameHi: "लहसुन",
      namePa: "ਲਸਣ",
      category: "vegetables",
      image: "https://images.unsplash.com/photo-1588615419957-462725e2e858?auto=format&fit=crop&w=600&q=80",
      fallbackIcon: "🧄",
      grade: "Ooty / Desi G-282",
      unit: "Quintal (100 kg)",
      allIndiaAvg: 11200,
      priceTrend: "+ ₹450 (4.2%)",
      trendDirection: "up",
      msp: 0,
      season: "Rabi",
      bestSowing: "Sep - Nov",
      harvestTime: "Feb - Apr",
      description: "White bold tight cloves garlic, dry cured."
    }
  ],

  mandis: [], // Will be populated dynamically via API

  vehicles: [
    {
      id: "tractor",
      name: "Tractor Trolley",
      nameHi: "ट्रैक्टर ट्रॉली",
      namePa: "ਟਰੈਕਟਰ ਟਰਾਲੀ",
      icon: "🚜",
      capacityQtl: 40,
      capacityBags: 80,
      ratePerKm: 28,
      baseLoadingFee: 400,
      speedKmh: 30,
      description: "Best for village roads & loads between 20 to 50 quintals.",
      badge: "Farmer Favorite"
    },
    {
      id: "pickup",
      name: "Pickup Bolero Camper",
      nameHi: "पिकअप बोलेरो",
      namePa: "ਪਿਕਅੱਪ ਬੋਲੇਰੋ",
      icon: "🛻",
      capacityQtl: 20,
      capacityBags: 40,
      ratePerKm: 18,
      baseLoadingFee: 250,
      speedKmh: 50,
      description: "Fast transit, ideal for perishables (vegetables & fruits) up to 25 quintals.",
      badge: "Fast & Safe"
    },
    {
      id: "auto",
      name: "3-Wheeler Cargo Auto",
      nameHi: "3-पहिया ऑटो रिक्शा",
      namePa: "3-ਪਹੀਆ ਆਟੋ",
      icon: "🛺",
      capacityQtl: 8,
      capacityBags: 16,
      ratePerKm: 12,
      baseLoadingFee: 120,
      speedKmh: 35,
      description: "Economical for small quantities up to 10 quintals to nearby mandis.",
      badge: "Lowest Cost"
    },
    {
      id: "truck",
      name: "10-Wheeler Heavy Truck",
      nameHi: "10-टायर बड़ा ट्रक",
      namePa: "10-ਟਾਇਰ ਵੱਡਾ ਟਰੱਕ",
      icon: "🚛",
      capacityQtl: 160,
      capacityBags: 320,
      ratePerKm: 52,
      baseLoadingFee: 1200,
      speedKmh: 45,
      description: "Heavy bulk transport for 100+ quintals across long interstate distances.",
      badge: "Bulk Transport"
    }
  ],

  priceHistory: {}, // Fetched via API
  weather: {}, // Fetched via API
  sampleAlerts: [] // Fetched via API
};

if (typeof window !== "undefined") {
  window.AGRI_DATA = AGRI_DATA;
}
